// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkcM_zKA95eWiqPhfYM5vD5NZQwpeY0k',
    appId: '1:922181444759:web:05fa82dce832bca9cdb5d2',
    messagingSenderId: '922181444759',
    projectId: 'blackcoffer-internship-871cc',
    authDomain: 'blackcoffer-internship-871cc.firebaseapp.com',
    storageBucket: 'blackcoffer-internship-871cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiKPvXarb8Ba3tNLJG-ecidw4lapMkqJ4',
    appId: '1:922181444759:android:1f8703f0f8a6812bcdb5d2',
    messagingSenderId: '922181444759',
    projectId: 'blackcoffer-internship-871cc',
    storageBucket: 'blackcoffer-internship-871cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHmfFWDc_s5TUv-Gs-VaQNDlMl6aLqOz0',
    appId: '1:922181444759:ios:53eab49b8ab03994cdb5d2',
    messagingSenderId: '922181444759',
    projectId: 'blackcoffer-internship-871cc',
    storageBucket: 'blackcoffer-internship-871cc.appspot.com',
    iosBundleId: 'com.example.blackcofferTestAssignment',
  );
}
